Use py.test instead of plain python for test
Example output:

```
tests/test.py F                                                                                                                                        [100%]

========================================================================== FAILURES ==========================================================================
_____________________________________________________________________ test_missing_parts _____________________________________________________________________

    def test_missing_parts():
        for needle in sorted(needles):
            jsonfile = os.path.join(needledir, needle + '.json')
            pngfile = os.path.join(needledir, needle + '.png')

            # Check for file existence
            assert os.path.isfile(jsonfile), "Needle '{}' is missing its JSON file!".format(needle)
>           assert os.path.isfile(pngfile), "Needle '{}' is missing its PNG file!".format(needle)
E           AssertionError: Needle 'foo' is missing its PNG file!
E           assert False
E            +  where False = <function isfile at 0x7f297d413950>('/home/okurz/local/os-autoinst/os-autoinst-distri-opensuse/products/opensuse/needles/tests/../foo.png')
E            +    where <function isfile at 0x7f297d413950> = <module 'posixpath' from '/usr/lib64/python3.6/posixpath.py'>.isfile
E            +      where <module 'posixpath' from '/usr/lib64/python3.6/posixpath.py'> = os.path

tests/test.py:26: AssertionError
================================================================== 1 failed in 0.18 seconds ==================================================================
```